/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    media: Media;
    enquiries: Enquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'practice-page': PracticePage;
    'studio-details': StudioDetail;
  };
  globalsSelect: {
    'practice-page': PracticePageSelect<false> | PracticePageSelect<true>;
    'studio-details': StudioDetailsSelect<false> | StudioDetailsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The complete archive, numbered chronologically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Archive number, e.g. 014. Zero-padded to three digits.
   */
  no: string;
  name: string;
  /**
   * The project's URL. Changing this breaks existing links, including the ones inherited from the old site.
   */
  slug: string;
  /**
   * e.g. Hackney, E8. An em dash if unknown.
   */
  place?: string | null;
  /**
   * Provisional until confirmed. An em dash if unknown.
   */
  year?: string | null;
  sector: 'houses' | 'eat-drink' | 'objects' | 'public';
  /**
   * Specific description, e.g. HOUSE / LOFT EXTENSION. Shown in caps.
   */
  type: string;
  /**
   * e.g. BUILT, PLANNING GRANTED, COMPETITION WIN, STATUS TO CONFIRM.
   */
  status: string;
  /**
   * Prints the status in oxide. Tick for anything not built.
   */
  unbuilt?: boolean | null;
  /**
   * Credited on the project's cover and in the credits line.
   */
  photographer?: string | null;
  /**
   * Awards and coverage. These drive the Press page, so it can never fall out of date.
   */
  press?:
    | {
        entry: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The practice's own words. Plain paragraphs rather than rich text: the design gives the essay one voice and no inline formatting.
   */
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * In order. The first is the project's cover, used on the homepage, the archive and as the case-study hero.
   */
  figures?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Uploaded originals. The published derivatives are generated separately; see docs/content-open-questions.md.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * How this image is listed, e.g. "Latimer Road, fig. 03". Not shown on the site.
   */
  title?: string | null;
  /**
   * Only for images that carry meaning on their own. Decorative or purely illustrative images can be left blank.
   */
  alt?: string | null;
  /**
   * Set in the practice's own voice, e.g. 'The suite as one plan'. Printed in caps beneath the image.
   */
  caption?: string | null;
  /**
   * Declared beneath every image. 'Not yet established' prints nothing rather than a meaningless label.
   */
  medium?: ('PHOTOGRAPH' | 'DRAWING' | 'MODEL' | 'VISUALISATION' | 'IMAGE') | null;
  /**
   * Photographer or author, if known.
   */
  credit?: string | null;
  /**
   * Cropping a photograph is art direction; cropping a plan destroys what it exists to show.
   */
  fit?: ('cover' | 'contain') | null;
  /**
   * Filled in by the media pipeline.
   */
  derivative?: {
    src?: string | null;
    width?: number | null;
    height?: number | null;
    /**
     * Only used by the splash: which single flat colour the mark should be over this photograph. Sampled from the centre of the image, where the mark sits.
     */
    tone?: ('light' | 'dark') | null;
  };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Messages sent from the contact page. Newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  /**
   * Where the site is.
   */
  location?: string | null;
  work?: ('houses' | 'eat-drink' | 'objects' | 'public' | 'other') | null;
  message: string;
  /**
   * The practice's own note. The only field here that can be changed.
   */
  status?: ('new' | 'replied' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can sign in and edit the archive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Editors can change everything in the archive. Owners can also add, remove and change accounts.
   */
  role?: ('owner' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  no?: T;
  name?: T;
  slug?: T;
  place?: T;
  year?: T;
  sector?: T;
  type?: T;
  status?: T;
  unbuilt?: T;
  photographer?: T;
  press?:
    | T
    | {
        entry?: T;
        id?: T;
      };
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  figures?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  medium?: T;
  credit?: T;
  fit?: T;
  derivative?:
    | T
    | {
        src?: T;
        width?: T;
        height?: T;
        tone?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  location?: T;
  work?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-page".
 */
export interface PracticePage {
  id: number;
  /**
   * The display line at the top of the page.
   */
  statement: string;
  paragraphs?:
    | {
        /**
         * Leave blank to continue the essay. Fill it in to start a new section, the way Process does.
         */
        heading?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. ACCREDITATION, EDUCATION, PREVIOUS PRACTICES.
   */
  credentials?:
    | {
        label: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  recognition?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  colleagues?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  collaborators?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-details".
 */
export interface StudioDetail {
  id: number;
  /**
   * The display statement on the homepage.
   */
  positioningLine: string;
  /**
   * The display line on the contact page.
   */
  contactStatement: string;
  contactLede: string;
  email: string;
  telephone: string;
  /**
   * What the landing page shows. Nothing here is deleted when it is switched off.
   */
  homepage?: {
    /**
     * The display line above the work. Off at the practice's request.
     */
    showStatement?: boolean | null;
    /**
     * Number, type, place and press. Off leaves the name alone.
     */
    showProjectFacts?: boolean | null;
    showSectorFilter?: boolean | null;
    /**
     * The mark on a full screen, then a photograph, until the visitor dismisses it.
     */
    splashEnabled?: boolean | null;
    /**
     * Shown behind the mark, in this order, changing every few seconds. One is fine: with a single photograph nothing cycles. With none, the splash stays on paper, which is also a valid state. Drag to reorder.
     */
    splashSlides?:
      | {
          /**
           * Used on desktop, and on phones held sideways.
           */
          landscape: number | Media;
          /**
           * For phones, where a landscape crop loses the subject. Left empty, the landscape one is used and cropped.
           */
          portrait?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * London and Cape Town. The city name prints in mono above the address.
   */
  addresses?:
    | {
        city: string;
        lines: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practice-page_select".
 */
export interface PracticePageSelect<T extends boolean = true> {
  statement?: T;
  paragraphs?:
    | T
    | {
        heading?: T;
        text?: T;
        id?: T;
      };
  credentials?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  recognition?:
    | T
    | {
        text?: T;
        id?: T;
      };
  colleagues?:
    | T
    | {
        name?: T;
        id?: T;
      };
  collaborators?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-details_select".
 */
export interface StudioDetailsSelect<T extends boolean = true> {
  positioningLine?: T;
  contactStatement?: T;
  contactLede?: T;
  email?: T;
  telephone?: T;
  homepage?:
    | T
    | {
        showStatement?: T;
        showProjectFacts?: T;
        showSectorFilter?: T;
        splashEnabled?: T;
        splashSlides?:
          | T
          | {
              landscape?: T;
              portrait?: T;
              id?: T;
            };
      };
  addresses?:
    | T
    | {
        city?: T;
        lines?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}